name: CI and Release

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup yarn version
        run: corepack enable && yarn set version 4.4.1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Build
        run: yarn build

  release:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup yarn version
        run: corepack enable && yarn set version 4.4.1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
